# Generated by Django 4.2.11 on 2024-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_activeuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='gate_pass_approve_flag',
            field=models.BooleanField(default=False),
        ),
    ]
