# Generated by Django 4.2.11 on 2024-09-04 10:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employeeuser_gate_pass_approve_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.EmployeeUser.profile_image_path),
        ),
    ]
