# Generated by Django 4.2.11 on 2024-08-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subordinate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='gst_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
