# Generated by Django 4.2.11 on 2024-08-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='delivers_dates',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='e_way_bills_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
