# Generated by Django 4.2.11 on 2024-08-06 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0002_deliverychallan_delivers_dates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePassApproverDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_status', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('approver_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_pass_approver_details', to=settings.AUTH_USER_MODEL)),
                ('gate_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_pass_approver_details', to='tracking.gatepassinfo')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GatePassApproverDetails',
                'unique_together': {('gate_info', 'emp')},
            },
        ),
    ]
