# Generated by Django 4.2.11 on 2024-08-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_gatepassinfo_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepassapproverdetails',
            name='status_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
