# Generated by Django 4.2.11 on 2024-08-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_gatepassapproverdetails_approve_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepassapproverdetails',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
