# Generated by Django 4.2.11 on 2024-08-07 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0007_gatepassapproverdetails_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePassAuthThreads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_pass_auth_threads', to=settings.AUTH_USER_MODEL)),
                ('gate_pass_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_pass_auth_threads', to='tracking.gatepassinfo')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GatePassAuthThreads',
            },
        ),
    ]
