# Generated by Django 4.2.11 on 2024-08-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_gatepassauththreads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepassinfo',
            name='gate_pass_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
