# Generated by Django 4.2.11 on 2024-08-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_remove_gatepassapproverdetails_approve_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcinvoicedetails',
            name='eway_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcinvoicedetails',
            name='eway_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
