# Generated by Django 4.2.11 on 2024-08-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_dcinvoicedetails_eway_bill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcinvoicedetails',
            name='bill_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
